name = ML Pipeline

on:
  push:
    branches: [ main ]


jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pip install -r deployment/requirements.txt
      
    - name: Run Training
      run: python -m src/train_model.py