

name: ML Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r superkart/requirements.txt

    - name: Login to Hugging Face
      run: |
        pip install huggingface_hub
        huggingface-cli login --token ${{ secrets.HF_TOKEN }}

    - name: Data Preprocessing
      run: python superkart/src/preprocess.py

    - name: Train model
      run: python superkart/src/train.py

    - name: model Evaluation
      run: python superkart/src/evaluate.py
      
     
